import type { Challenge } from "@/lib/types"

export const challenges: Challenge[] = [
  {
    id: "ch-001",
    title: "First Date",
    description: "Build a first-date outfit chosen by chaos — bold but approachable.",
    category: "Moods",
    boldness: 3,
    participationCount: 12847,
    emoji: "💘",
    color: "#FF6B6B",
  },
  {
    id: "ch-002",
    title: "Quiet Luxury",
    description: "Dress like old money. Subtle, refined, and effortlessly expensive.",
    category: "Moods",
    boldness: 2,
    participationCount: 23104,
    emoji: "🥂",
    color: "#C9B99A",
  },
  {
    id: "ch-003",
    title: "90s Streetwear",
    description: "Create a 90s streetwear comeback. Baggy, bold, and unapologetically nostalgic.",
    category: "Decades",
    boldness: 4,
    participationCount: 18932,
    emoji: "📼",
    color: "#7C3AED",
  },
  {
    id: "ch-004",
    title: "Festival Mode",
    description: "You are headlining Coachella. Dress accordingly.",
    category: "Events",
    boldness: 5,
    participationCount: 31250,
    emoji: "🎪",
    color: "#F59E0B",
  },
  {
    id: "ch-005",
    title: "Cyberpunk Office",
    description: "Tech dystopia meets corporate dress code. Neon meets neutral.",
    category: "Moods",
    boldness: 5,
    participationCount: 8741,
    emoji: "🤖",
    color: "#06B6D4",
  },
  {
    id: "ch-006",
    title: "Main Character",
    description: "This is your movie. Dress like everyone is watching.",
    category: "Moods",
    boldness: 4,
    participationCount: 45612,
    emoji: "🎬",
    color: "#EC4899",
  },
  {
    id: "ch-007",
    title: "Mystery Look",
    description: "The algorithm decides. Trust the process.",
    category: "Wildcards",
    boldness: 3,
    participationCount: 9823,
    emoji: "🎭",
    color: "#8B5CF6",
  },
  {
    id: "ch-008",
    title: "Wildcard",
    description: "Pure chaos. No rules. Maximum fashion energy.",
    category: "Wildcards",
    boldness: 5,
    participationCount: 7234,
    emoji: "🃏",
    color: "#EF4444",
  },
  {
    id: "ch-009",
    title: "Startup at Paris Fashion Week",
    description: "Dress like a startup founder attending Paris Fashion Week.",
    category: "Events",
    boldness: 4,
    participationCount: 15420,
    emoji: "🗼",
    color: "#10B981",
  },
  {
    id: "ch-010",
    title: "Villain Era",
    description: "Dress like the villain in a luxury fashion campaign.",
    category: "Moods",
    boldness: 5,
    participationCount: 28901,
    emoji: "🖤",
    color: "#1F2937",
  },
  {
    id: "ch-011",
    title: "Color Dare",
    description: "Try a color you would normally avoid. Commit fully.",
    category: "Wildcards",
    boldness: 3,
    participationCount: 19234,
    emoji: "🎨",
    color: "#F97316",
  },
]

export function getChallengeById(challengeId: string): Challenge | null {
  return challenges.find((challenge) => challenge.id === challengeId) ?? null
}
